name: Frequent Cleanup Registry Data

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  cleanup-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete registry data
        run: |
          rm -rf ./data/*
          git add .
          git commit -m 'Remove registry data'
          git push