name: Sync Private Data
on: [push]
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        
      - name: Checkout Private Data Repo
        uses: actions/checkout@v3
        with:
          repository: erdd-erdi/registry-data
          path: data
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Remove data folder if it was added as a submodule
        run: |
          git submodule deinit -f data || true
          git rm --cached data || true
          git commit -m "Removed data folder (submodule or cache)"
        
      - name: Sync private data to public repo
        run: |
          # Make sure the data is in the right location
          cp -r data/* .
          
      - name: Commit the sync and push changes
        run: |
          git config --global user.name "erdd-erdi"
          git config --global user.email "mcordel@adb.org"
          git add .
          git commit -m "Sync private data"
          git push
