name: Sync Private Data
on: [push]
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        
      - name: Checkout Private Data Repo
        uses: actions/checkout@v3
        with:
          repository: erdd-erdi/registry-data
          path: data
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set Git Identity
        run: |
          git config --global user.name "erdd-erdi"
          git config --global user.email "mcordel@adb.org"
        
      - name: Remove data folder if it was added as a submodule
        run: |
          git submodule deinit -f data || true
          git rm --cached data || true
          git add .gitmodules
          git commit -m "Removed data folder (submodule or cache)" || true

      - name: Sync private data to public repo
        run: |
          # Copy the data from the private repo into the public repo
          cp -r data/* .

      - name: Set up SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Commit the sync and push changes
        run: |
          git add .
          git commit -m "Sync private data"
          git push git@github.com:erdd-erdi/erdd-erdi.github.io.git
