name: Sync Private Data
on: [push]
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        
      - name: Checkout Private Data Repo
        uses: actions/checkout@v3
        with:
          repository: erdi-erdd/cert-data
          path: data
          ssh-key: ${{ secrets.DEPLOY_KEY }}
