name: Sync Private Data to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the public repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Set up Git identity for commits
      - name: Set up Git user
        run: |
          git config --global user.email "mcordel@adb.org"
          git config --global user.name "erdd-erdi"

      # Fetch the latest changes in the private repo
      - name: Fetch private data from private repo
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/erdd-erdi/registry-data.git data
          cd data
          git fetch --all
          git pull origin main

      # Copy the data into your main repository
      - name: Copy data to main repository
        run: |
          cp -r data/* .

      # Stage and commit the changes
      - name: Commit data
        run: |
          git add .
          git commit -m "Sync private data with submodule changes"

      # Push changes using GITHUB_TOKEN
      - name: Push changes to public repo
        run: |
          git push https://github.com/${{ github.repository_owner }}/erdd-erdi.github.io HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
